import sys
import os
from unittest.mock import MagicMock, patch
from langchain_core.runnables import RunnableLambda
from langchain_core.messages import AIMessage

# Set paths
current_dir = os.getcwd()
if current_dir.endswith("backend"):
    sys.path.append(current_dir)
else:
    sys.path.append(os.path.join(current_dir, "backend"))

# Mock LLM and RAG
def mock_llm_func(input):
    return AIMessage(content="Mocked Post-Mortem Content generated by AI")

def run_tests():
    print("Starting Verification...")

    # Patch LLM before importing modules that might use it
    # Import app.llm first to ensure it exists for patching
    import app.llm
    with patch("app.llm.get_llm", return_value=RunnableLambda(mock_llm_func)):
        from app.db import init_db, SessionLocal, Service, Runbook
        # bootstrap_catalog is called on import of runbooks, so this triggers it
        from app.tools.runbooks import lookup_service, list_runbooks, bootstrap_catalog
        from app.tools.incident import create_incident, generate_postmortem
        from app.tools.real import check_on_call_schedule

        # Ensure DB init
        init_db()
        # Run bootstrap again in case it failed during import
        bootstrap_catalog()

        # 1. Verify DB Population
        db = SessionLocal()
        s_count = db.query(Service).count()
        r_count = db.query(Runbook).count()
        print(f"DB Check: {s_count} Services, {r_count} Runbooks.")

        if s_count == 0 or r_count == 0:
            print("FAILED: DB not populated.")
            sys.exit(1)

        # 2. Verify Runbook Tool (DB access)
        res = lookup_service.invoke({"service_name": "payment-api"})
        print(f"lookup_service output: {res[:50]}...")
        if "payment-api" not in res:
             print("FAILED: lookup_service didn't return expected data.")
             sys.exit(1)

        # 3. Verify New SRE Tool
        on_call = check_on_call_schedule.invoke({"schedule_id": "primary"})
        print(f"on_call output: {on_call}")
        if "Alice" not in on_call:
             print("FAILED: check_on_call_schedule failed.")
             sys.exit(1)

        # 4. Verify Post-Mortem (with RAG and LLM Mock)
        # Create incident
        inc_msg = create_incident.invoke({"title": "Test Verification", "severity": "SEV-1", "description": "Database connection timeout in payment-api"})
        inc_id = inc_msg.split("ID: ")[1].strip()
        print(f"Created Incident: {inc_id}")

        # Generate PM
        pm_msg = generate_postmortem.invoke({"incident_id": inc_id})
        print(f"generate_postmortem output: {pm_msg}")

        if "Post-Mortem generated" not in pm_msg:
             print("FAILED: generate_postmortem failed.")
             sys.exit(1)

        print("\nSUCCESS: All features verified!")

if __name__ == "__main__":
    run_tests()
